# Generated by Django 3.2.3 on 2021-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioBook_ID', models.IntegerField(max_length=100, unique=True)),
                ('Title', models.TextField(max_length=100)),
                ('Author', models.TextField(max_length=100)),
                ('Narrator', models.TextField(max_length=100)),
                ('duration', models.PositiveIntegerField(max_length=20)),
                ('Uploaded_Time', models.DateTimeField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Podcast_ID', models.IntegerField(max_length=100, unique=True)),
                ('Name', models.TextField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('Uploaded_Time', models.DateTimeField()),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.CharField(max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='Song_ID',
            field=models.IntegerField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='Uploaded_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
