# Generated by Django 3.2.3 on 2021-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210514_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='Song_ID',
            field=models.IntegerField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='Uploaded_Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
