# Generated by Django 3.2.3 on 2021-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210515_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
